version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-abhipreet}"
    image: cybulde-data-versioning
    container_name: cybulde-data-versioning-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-abhipreet}"
        USER_ID : "${USER_ID:-1000}"
        GIT_EMAIL : "${GIT_EMAIL:-abhipreets2@gmail.com}"
        GIT_USERNAME : "${GIT_USERNAME:-abhipreets2}"
    volumes:
      - ./:/app/
      - /home/abhipreet/.config/gcloud:/home/${USER_NAME:-abhipreet}/.config/gcloud
      - /home/abhipreet/.ssh:/home/${USER_NAME:-abhipreet}/.ssh
