version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-abhipreet}"
    image: cybulde-data-preparation
    container_name: cybulde-data-preparation-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-abhipreet}"
        USER_ID : "${USER_ID:-1000}"
      
